# Generated by Django 5.2.11 on 2026-02-20 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressTrackerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='progress_trackers/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Файл трекера прогресса',
                'verbose_name_plural': 'Файл трекера прогресса',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('is_top', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='my_study.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='my_study.subject')),
            ],
            options={
                'ordering': ['school__name', 'title'],
                'unique_together': {('school', 'title')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('probnik', 'Пробник'), ('test', 'Тестирование'), ('olymp', 'Олимпиада'), ('essay', 'Итоговое сочинение'), ('other', 'Другое')], max_length=10)),
                ('title', models.CharField(help_text='Например: Пробник ЕГЭ от … / Тур олимпиады …', max_length=200)),
                ('date', models.DateField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('max_score', models.FloatField(blank=True, null=True)),
                ('place', models.CharField(blank=True, help_text='Место/уровень/организатор', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, upload_to='assessments/%Y/%m/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='my_study.subject')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CourseSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.TextField(help_text='Почему вы выбрали этот курс/направление?')),
                ('need_tutor', models.BooleanField(default=False, help_text='Нужен куратор')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='my_study.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='UniversityPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Город')),
                ('specialty', models.CharField(blank=True, max_length=200, verbose_name='Специальность/направление')),
                ('is_targeted', models.BooleanField(default=False, verbose_name='Целевое обучение')),
                ('priority', models.PositiveIntegerField(help_text='1 — самый высокий приоритет')),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('subjects', models.ManyToManyField(blank=True, to='my_study.subject', verbose_name='Предметы для специальности')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uni_priorities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority'],
                'constraints': [models.UniqueConstraint(fields=('user', 'priority'), name='unique_priority_per_user'), models.UniqueConstraint(fields=('user', 'university', 'specialty'), name='unique_uni_specialty_per_user')],
            },
        ),
    ]
