version: '3.9'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env


  db:
    image: postgres:15
    environment:
      POSTGRES_DB: putevka
      POSTGRES_USER: vukish
      POSTGRES_PASSWORD: boost25!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vukish -d putevka"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
