# Generated by Django 5.2.14 on 2026-05-11 08:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationLetterInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Инструкция к мотивационному письму', max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, default='Перед написанием мотивационного письма ознакомьтесь с инструкциями.', verbose_name='Текст')),
                ('url', models.URLField(blank=True, default='', verbose_name='Ссылка на инструкцию')),
                ('button_text', models.CharField(default='Открыть инструкцию', max_length=80, verbose_name='Текст кнопки')),
                ('file', models.FileField(blank=True, help_text='Устаревшее поле. Используется как запасной вариант, если ссылка на инструкцию не задана.', null=True, upload_to='motivation/instructions/', verbose_name='Общий файл инструкции')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать плашку')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Инструкция к мотивационному письму',
                'verbose_name_plural': 'Инструкция к мотивационному письму',
                'ordering': ['-updated_at', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MotivationLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False, verbose_name='Мотивационное письмо принято')),
                ('deadline_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дедлайн сдачи мотивационного письма')),
                ('letter_text', models.TextField(blank=True, help_text='Вставьте своё мотивационное письмо сюда', verbose_name='Текст мотивационного письма')),
                ('is_favorite', models.BooleanField(db_index=True, default=False, verbose_name='Избранное письмо')),
                ('admin_score', models.PositiveSmallIntegerField(blank=True, help_text='Введите значение от 0 до 70', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)], verbose_name='Итоговый балл')),
                ('admin_rating', models.TextField(blank=True, null=True, verbose_name='Оценка администратора')),
                ('revision_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий на доработку (видит соискатель)')),
                ('revision_requested_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Отправлено на доработку в')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлено'), ('revision', 'На дописывании')], db_index=True, default='draft', max_length=10, verbose_name='Статус')),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Отправлено в')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motivation_letters_revision_requested', to=settings.AUTH_USER_MODEL, verbose_name='Кто отправил на доработку')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motivation_letter', to=settings.AUTH_USER_MODEL, verbose_name='Стипендиат')),
            ],
            options={
                'verbose_name': 'Мотивационное письмо',
                'verbose_name_plural': 'Мотивационные письма',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MotivationLetterRubricReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
                ('model_name', models.CharField(blank=True, default='', max_length=64, verbose_name='Модель ИИ')),
                ('schema_version', models.CharField(blank=True, default='v3.0-2026-04-25', max_length=32, verbose_name='Версия рубрики')),
                ('char_count', models.PositiveIntegerField(default=0, help_text='По новой рубрике важен объём письма в символах', verbose_name='Количество символов')),
                ('word_count', models.PositiveIntegerField(default=0, verbose_name='Количество слов')),
                ('total_score', models.IntegerField(default=0, verbose_name='Итоговый балл')),
                ('specialty_choice_score', models.CharField(choices=[('10', 'Да, развёрнуто и материалы учтены — 10'), ('5', 'Да, но кратко/гипотетически, материалы учтены — 5'), ('2', 'Да, но кратко/гипотетически, материалы не учтены — 2'), ('0', 'Нет — 0')], default='0', max_length=2, verbose_name='Тема №2: выбор специальности')),
                ('university_choice_score', models.CharField(choices=[('10', 'Да, развёрнуто и материалы учтены — 10'), ('5', 'Да, но кратко/гипотетически, материалы учтены — 5'), ('2', 'Да, но кратко/гипотетически, материалы не учтены — 2'), ('0', 'Нет — 0')], default='0', max_length=2, verbose_name='Тема №3: выбор вуза')),
                ('current_preparation_score', models.CharField(choices=[('10', 'Да, развёрнуто и по существу — 10'), ('5', 'Да, но кратко/гипотетически — 5'), ('0', 'Нет — 0')], default='0', max_length=2, verbose_name='Тема №4: текущая подготовка')),
                ('admission_trajectory_score', models.CharField(choices=[('10', 'Да, развёрнуто; есть обоснование; материалы учтены — 10'), ('5', 'Да, кратко/гипотетически; есть обоснование; материалы учтены — 5'), ('2', 'Да, кратко/гипотетически; нет обоснования ИЛИ материалы не учтены — 2'), ('0', 'Нет — 0')], default='0', max_length=2, verbose_name='Тема №5: траектория поступления')),
                ('next_year_preparation_score', models.CharField(choices=[('10', 'Да, развёрнуто и по существу — 10'), ('5', 'Да, но кратко/гипотетически — 5'), ('0', 'Нет — 0')], default='0', max_length=2, verbose_name='Тема №6: подготовка в следующем учебном году')),
                ('higher_education_value_score', models.CharField(choices=[('10', 'Да, развёрнуто и по существу — 10'), ('5', 'Да, но кратко/гипотетически — 5'), ('0', 'Нет — 0')], default='0', max_length=2, verbose_name='Тема №7: значимость высшего образования')),
                ('support_criticality_score', models.CharField(choices=[('10', 'Да, развёрнуто и по существу — 10'), ('5', 'Да, но кратко/гипотетически — 5'), ('0', 'Нет — 0')], default='0', max_length=2, verbose_name='Тема №8: критичность поддержки')),
                ('composition_penalty', models.CharField(choices=[('0', 'Нет замечаний — 0'), ('-2', 'Незначительные проблемы — -2'), ('-5', 'Серьёзные проблемы — -5')], default='0', max_length=2, verbose_name='Последовательность изложения и композиция')),
                ('style_penalty', models.CharField(choices=[('0', 'Нет замечаний — 0'), ('-2', 'Незначительные проблемы — -2'), ('-5', 'Серьёзные проблемы — -5')], default='0', max_length=2, verbose_name='Точность и выразительность речи')),
                ('orthography_penalty', models.CharField(choices=[('0', 'Нет замечаний — 0'), ('-2', 'Незначительные проблемы — -2'), ('-5', 'Серьёзные проблемы — -5')], default='0', max_length=2, verbose_name='Орфография')),
                ('syntax_penalty', models.CharField(choices=[('0', 'Нет замечаний — 0'), ('-2', 'Незначительные проблемы — -2'), ('-5', 'Серьёзные проблемы — -5')], default='0', max_length=2, verbose_name='Синтаксис')),
                ('is_too_short', models.BooleanField(default=False, verbose_name='Менее 1000 символов')),
                ('score_capped_for_short_length', models.BooleanField(default=False, help_text='По критериям максимум 70 для такого объёма не ставится', verbose_name='Для текста 1000–1500 символов применён потолок оценки')),
                ('suspected_ai_generated', models.BooleanField(default=False, verbose_name='Есть признаки написания нейросетью')),
                ('returned_for_revision', models.BooleanField(default=False, verbose_name='Рекомендовано вернуть на доработку')),
                ('reviewer_comment', models.TextField(blank=True, default='', verbose_name='Комментарий проверяющего')),
                ('family', models.TextField(blank=True, default='', verbose_name='Семья')),
                ('hobbies', models.TextField(blank=True, default='', verbose_name='Увлечения')),
                ('achievements', models.TextField(blank=True, default='', verbose_name='Достижения')),
                ('traits', models.TextField(blank=True, default='', verbose_name='Личные качества')),
                ('school_teachers', models.TextField(blank=True, default='', verbose_name='Школа и преподаватели')),
                ('prep_subjects', models.TextField(blank=True, default='', verbose_name='Предметы для подготовки')),
                ('specialty', models.TextField(blank=True, default='', verbose_name='Специальность')),
                ('preferred_universities', models.TextField(blank=True, default='', verbose_name='Предпочитаемые вузы')),
                ('relocation', models.TextField(blank=True, default='', verbose_name='Возможность переезда')),
                ('olympiads', models.TextField(blank=True, default='', verbose_name='Участие в олимпиадах')),
                ('motivation', models.TextField(blank=True, default='', verbose_name='Мотивация')),
                ('help_criticality', models.TextField(blank=True, default='', verbose_name='Критичность помощи')),
                ('extra', models.TextField(blank=True, default='', verbose_name='Дополнительные данные')),
                ('justification', models.TextField(blank=True, default='', verbose_name='Пояснение эксперта')),
                ('letter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_review', to='core.motivationletter', verbose_name='Мотивационное письмо')),
            ],
            options={
                'verbose_name': 'Оценка мотивационного письма по рубрике',
                'verbose_name_plural': 'Оценки мотивационных писем по рубрике',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Оповещение',
                'verbose_name_plural': 'Оповещения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя пользователя Telegram')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('language_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Языковой код')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('activation_token', models.UUIDField(blank=True, default=uuid.uuid4, help_text='Уникальный токен для активации аккаунта через Telegram.', null=True, unique=True, verbose_name='Токен активации Telegram')),
                ('telegram_verified', models.BooleanField(default=False, help_text='Определяет, активирован ли пользовательский аккаунт на сайте после привязки Telegram.', verbose_name='Активен ли веб-аккаунт')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_account', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Аккаунт Telegram',
                'verbose_name_plural': 'Аккаунты Telegram',
            },
        ),
        migrations.CreateModel(
            name='RegistrationPersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email, введенный пользователем.', max_length=254, unique=True)),
                ('password', models.CharField(help_text='Хешированный пароль пользователя.', max_length=128)),
                ('email_verification_code', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='Токен для подтверждения email')),
                ('email_code_sent_at', models.DateTimeField(blank=True, help_text='Время истечения срока действия кода email.', null=True)),
                ('email_code_expires_at', models.DateTimeField(blank=True, help_text='Время истечения срока действия кода email.', null=True)),
                ('email_verified', models.BooleanField(default=False, help_text='True, если email был успешно подтвержден.')),
                ('phone', models.CharField(blank=True, help_text='Номер телефона, введенный пользователем (если не из Telegram).', max_length=20, null=True)),
                ('phone_verified', models.BooleanField(default=False, help_text='True, если номер телефона был успешно подтвержден.')),
                ('current_step', models.CharField(choices=[('initial_data', 'Ввод начальных данных'), ('email_verification', 'Подтверждение Email'), ('telegram_connection', 'Подключение Telegram'), ('phone_verification_needed', 'Требуется подтверждение телефона'), ('phone_verification_code', 'Ввод кода подтверждения телефона'), ('finish', 'Завершение регистрации')], default='initial_data', help_text='Текущий шаг в процессе регистрации.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Ссылка на созданного пользователя после завершения регистрации.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('telegram_account', models.OneToOneField(blank=True, help_text='Ссылка на связанный TelegramAccount для активации.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.telegramaccount')),
            ],
            options={
                'verbose_name': 'Попытка регистрации',
                'verbose_name_plural': 'Попытки регистрации',
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('send_attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_seen', models.BooleanField(default=False, verbose_name='Просмотрено')),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Время просмотра')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.notification', verbose_name='Оповещение')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Получатель оповещения',
                'verbose_name_plural': 'Получатели оповещения',
                'ordering': ['-notification__created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='recipients',
            field=models.ManyToManyField(related_name='received_notifications', through='core.UserNotification', to=settings.AUTH_USER_MODEL, verbose_name='Получатели'),
        ),
        migrations.AddIndex(
            model_name='motivationletter',
            index=models.Index(fields=['status', 'submitted_at'], name='core_motiva_status_5c6ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='motivationletter',
            index=models.Index(fields=['created_at'], name='core_motiva_created_121c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='motivationletterrubricreview',
            index=models.Index(fields=['total_score'], name='core_motiva_total_s_2b7861_idx'),
        ),
        migrations.AddIndex(
            model_name='motivationletterrubricreview',
            index=models.Index(fields=['created_at'], name='core_motiva_created_93f808_idx'),
        ),
        migrations.AddIndex(
            model_name='motivationletterrubricreview',
            index=models.Index(fields=['schema_version'], name='core_motiva_schema__477824_idx'),
        ),
        migrations.AddIndex(
            model_name='motivationletterrubricreview',
            index=models.Index(fields=['is_too_short'], name='core_motiva_is_too__ec26a3_idx'),
        ),
        migrations.AddIndex(
            model_name='motivationletterrubricreview',
            index=models.Index(fields=['suspected_ai_generated'], name='core_motiva_suspect_ce2cd8_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramaccount',
            index=models.Index(fields=['telegram_id'], name='core_telegr_telegra_c53ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramaccount',
            index=models.Index(fields=['activation_token'], name='core_telegr_activat_5b2bd2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usernotification',
            unique_together={('notification', 'recipient')},
        ),
    ]
