# Generated by Django 5.2.11 on 2026-02-20 17:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationLetterInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Требования к мотивационному письму', max_length=200)),
                ('file', models.FileField(upload_to='motivation/instructions/')),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MotivationLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False, verbose_name='Мотивационное письмо принято')),
                ('deadline_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дедлайн сдачи мотивационного письма')),
                ('letter_text', models.TextField(blank=True, help_text='Вставьте своё мотивационное письмо сюда', verbose_name='Текст мотивационного письма')),
                ('admin_score', models.PositiveSmallIntegerField(blank=True, help_text='Введите значение от 0 до 60', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)], verbose_name='Итоговый балл')),
                ('admin_rating', models.TextField(blank=True, null=True, verbose_name='Оценка администратора')),
                ('revision_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий на доработку (видит соискатель)')),
                ('revision_requested_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Отправлено на доработку в')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлено'), ('revision', 'На дописывании')], db_index=True, default='draft', max_length=10, verbose_name='Статус')),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Отправлено в')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motivation_letters_revision_requested', to=settings.AUTH_USER_MODEL, verbose_name='Кто отправил на доработку')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motivation_letter', to=settings.AUTH_USER_MODEL, verbose_name='Стипендиат')),
            ],
            options={
                'verbose_name': 'Мотивационное письмо',
                'verbose_name_plural': 'Мотивационные письма',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MotivationLetterRubricReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
                ('model_name', models.CharField(blank=True, default='', max_length=64, verbose_name='Модель ИИ')),
                ('schema_version', models.CharField(blank=True, default='v1', max_length=32, verbose_name='Версия рубрики')),
                ('word_count', models.PositiveIntegerField(default=0, verbose_name='Количество слов')),
                ('total_score', models.IntegerField(default=0, verbose_name='Итоговый балл')),
                ('specialty_choice', models.CharField(choices=[('full', 'Полное раскрытие'), ('partial', 'Частично'), ('none', 'Не раскрыто')], max_length=16, verbose_name='Выбор специальности')),
                ('university_choice', models.CharField(choices=[('full', 'Полное раскрытие'), ('partial', 'Частично'), ('none', 'Не раскрыто')], max_length=16, verbose_name='Выбор университета')),
                ('current_preparation', models.CharField(choices=[('full', 'Полное раскрытие'), ('partial', 'Частично'), ('none', 'Не раскрыто')], max_length=16, verbose_name='Текущая подготовка')),
                ('next_year_plan', models.CharField(choices=[('full', 'Полное раскрытие'), ('partial', 'Частично'), ('none', 'Не раскрыто')], max_length=16, verbose_name='План на следующий год')),
                ('higher_ed_value', models.CharField(choices=[('full', 'Полное раскрытие'), ('partial', 'Частично'), ('none', 'Не раскрыто')], max_length=16, verbose_name='Ценность высшего образования')),
                ('support_criticality', models.CharField(choices=[('full', 'Полное раскрытие'), ('partial', 'Частично'), ('none', 'Не раскрыто')], max_length=16, verbose_name='Критичность поддержки')),
                ('composition', models.CharField(choices=[('good', 'Хорошая'), ('minor_issue', 'Незначительные проблемы'), ('major_issue', 'Серьёзные проблемы')], max_length=16, verbose_name='Композиция текста')),
                ('style_precision', models.CharField(choices=[('good', 'Точный стиль'), ('one_dimensional_or_imprecise', 'Однообразный / неточный'), ('poor', 'Плохой стиль')], max_length=32, verbose_name='Точность стиля')),
                ('orthography', models.CharField(choices=[('none', 'Ошибок нет'), ('one_two', '1–2 ошибки'), ('three_plus', '3 и более ошибок')], max_length=16, verbose_name='Орфография')),
                ('syntax', models.CharField(choices=[('none', 'Ошибок нет'), ('one', '1 ошибка'), ('two_plus', '2 и более ошибок')], max_length=16, verbose_name='Синтаксис')),
                ('family', models.TextField(blank=True, default='', verbose_name='Семья')),
                ('hobbies', models.TextField(blank=True, default='', verbose_name='Хобби')),
                ('achievements', models.TextField(blank=True, default='', verbose_name='Достижения')),
                ('traits', models.TextField(blank=True, default='', verbose_name='Личные качества')),
                ('school_teachers', models.TextField(blank=True, default='', verbose_name='Учителя')),
                ('prep_subjects', models.TextField(blank=True, default='', verbose_name='Предметы подготовки')),
                ('specialty', models.TextField(blank=True, default='', verbose_name='Предполагаемая специальность')),
                ('preferred_universities', models.TextField(blank=True, default='', verbose_name='Предпочтительные вузы')),
                ('relocation', models.TextField(blank=True, default='', verbose_name='Готовность к переезду')),
                ('olympiads', models.TextField(blank=True, default='', verbose_name='Олимпиады')),
                ('motivation', models.TextField(blank=True, default='', verbose_name='Мотивация')),
                ('help_criticality', models.TextField(blank=True, default='', verbose_name='Критичность помощи')),
                ('extra', models.TextField(blank=True, default='', verbose_name='Дополнительная информация')),
                ('justification', models.TextField(blank=True, default='', verbose_name='Пояснение эксперта')),
                ('letter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_review', to='core.motivationletter', verbose_name='Мотивационное письмо')),
            ],
            options={
                'verbose_name': 'Оценка мотивационного письма по рубрике',
                'verbose_name_plural': 'Оценки мотивационных писем по рубрике',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Оповещение',
                'verbose_name_plural': 'Оповещения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя пользователя Telegram')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('language_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Языковой код')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('activation_token', models.UUIDField(blank=True, default=uuid.uuid4, help_text='Уникальный токен для активации аккаунта через Telegram.', null=True, unique=True, verbose_name='Токен активации Telegram')),
                ('telegram_verified', models.BooleanField(default=False, help_text='Определяет, активирован ли пользовательский аккаунт на сайте после привязки Telegram.', verbose_name='Активен ли веб-аккаунт')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_account', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Аккаунт Telegram',
                'verbose_name_plural': 'Аккаунты Telegram',
            },
        ),
        migrations.CreateModel(
            name='RegistrationPersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email, введенный пользователем.', max_length=254, unique=True)),
                ('password', models.CharField(help_text='Хешированный пароль пользователя.', max_length=128)),
                ('email_verification_code', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='Токен для подтверждения email')),
                ('email_code_sent_at', models.DateTimeField(blank=True, help_text='Время истечения срока действия кода email.', null=True)),
                ('email_code_expires_at', models.DateTimeField(blank=True, help_text='Время истечения срока действия кода email.', null=True)),
                ('email_verified', models.BooleanField(default=False, help_text='True, если email был успешно подтвержден.')),
                ('phone', models.CharField(blank=True, help_text='Номер телефона, введенный пользователем (если не из Telegram).', max_length=20, null=True)),
                ('phone_verified', models.BooleanField(default=False, help_text='True, если номер телефона был успешно подтвержден.')),
                ('current_step', models.CharField(choices=[('initial_data', 'Ввод начальных данных'), ('email_verification', 'Подтверждение Email'), ('telegram_connection', 'Подключение Telegram'), ('phone_verification_needed', 'Требуется подтверждение телефона'), ('phone_verification_code', 'Ввод кода подтверждения телефона'), ('finish', 'Завершение регистрации')], default='initial_data', help_text='Текущий шаг в процессе регистрации.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Ссылка на созданного пользователя после завершения регистрации.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('telegram_account', models.OneToOneField(blank=True, help_text='Ссылка на связанный TelegramAccount для активации.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.telegramaccount')),
            ],
            options={
                'verbose_name': 'Попытка регистрации',
                'verbose_name_plural': 'Попытки регистрации',
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seen', models.BooleanField(default=False, verbose_name='Просмотрено')),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Время просмотра')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.notification', verbose_name='Оповещение')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Получатель оповещения',
                'verbose_name_plural': 'Получатели оповещения',
                'ordering': ['-notification__created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='recipients',
            field=models.ManyToManyField(related_name='received_notifications', through='core.UserNotification', to=settings.AUTH_USER_MODEL, verbose_name='Получатели'),
        ),
        migrations.AddIndex(
            model_name='motivationletter',
            index=models.Index(fields=['status', 'submitted_at'], name='core_motiva_status_5c6ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='motivationletter',
            index=models.Index(fields=['created_at'], name='core_motiva_created_121c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='motivationletterrubricreview',
            index=models.Index(fields=['total_score'], name='core_motiva_total_s_2b7861_idx'),
        ),
        migrations.AddIndex(
            model_name='motivationletterrubricreview',
            index=models.Index(fields=['created_at'], name='core_motiva_created_93f808_idx'),
        ),
        migrations.AddIndex(
            model_name='motivationletterrubricreview',
            index=models.Index(fields=['schema_version'], name='core_motiva_schema__477824_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramaccount',
            index=models.Index(fields=['telegram_id'], name='core_telegr_telegra_c53ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramaccount',
            index=models.Index(fields=['activation_token'], name='core_telegr_activat_5b2bd2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usernotification',
            unique_together={('notification', 'recipient')},
        ),
    ]
