# Generated by Django 5.2.14 on 2026-05-11 16:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('motivation_letter_review', 'Motivation letter review'), ('interview_transcription', 'Interview transcription'), ('scholar_video_transcription', 'Scholar video transcription'), ('interview_result_fill', 'Interview result fill')], db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('RETRY', 'Retry'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('source_app', models.CharField(db_index=True, max_length=64)),
                ('source_model', models.CharField(db_index=True, max_length=64)),
                ('source_object_id', models.PositiveIntegerField(db_index=True)),
                ('source_version', models.CharField(blank=True, default='', max_length=128)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('locked_by', models.CharField(blank=True, default='', max_length=128)),
                ('locked_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI task',
                'verbose_name_plural': 'AI tasks',
                'indexes': [models.Index(fields=['status', 'locked_until', 'created_at'], name='core_aitask_status_a64343_idx'), models.Index(fields=['source_app', 'source_model', 'source_object_id', 'task_type'], name='core_aitask_source__c39cb4_idx')],
            },
        ),
    ]
