# Generated by Django 5.2.14 on 2026-05-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aitask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivationletter',
            name='letter_text',
            field=models.TextField(blank=True, help_text='Вставьте своё мотивационное письмо сюда', max_length=20000, verbose_name='Текст мотивационного письма'),
        ),
    ]
