# Generated by Django 5.2.11 on 2026-03-11 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usernotification_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motivationletterrubricreview',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='motivationletterrubricreview',
            name='current_preparation',
        ),
        migrations.RemoveField(
            model_name='motivationletterrubricreview',
            name='higher_ed_value',
        ),
        migrations.RemoveField(
            model_name='motivationletterrubricreview',
            name='next_year_plan',
        ),
        migrations.RemoveField(
            model_name='motivationletterrubricreview',
            name='orthography',
        ),
        migrations.RemoveField(
            model_name='motivationletterrubricreview',
            name='specialty_choice',
        ),
        migrations.RemoveField(
            model_name='motivationletterrubricreview',
            name='style_precision',
        ),
        migrations.RemoveField(
            model_name='motivationletterrubricreview',
            name='support_criticality',
        ),
        migrations.RemoveField(
            model_name='motivationletterrubricreview',
            name='syntax',
        ),
        migrations.RemoveField(
            model_name='motivationletterrubricreview',
            name='university_choice',
        ),
        migrations.AddField(
            model_name='motivationletterrubricreview',
            name='admission_trajectory_score',
            field=models.CharField(choices=[('15', 'Да, развёрнуто; есть обоснование; материалы учтены — 15'), ('10', 'Да, кратко/гипотетически; есть обоснование; материалы учтены — 10'), ('5', 'Да, кратко/гипотетически; нет обоснования ИЛИ материалы не учтены — 5'), ('0', 'Нет — 0')], default='0', max_length=2, verbose_name='Тема №5: траектория поступления'),
        ),
        migrations.AddField(
            model_name='motivationletterrubricreview',
            name='char_count',
            field=models.PositiveIntegerField(default=0, help_text='По новой рубрике важен объём письма в символах', verbose_name='Количество символов'),
        ),
        migrations.AddField(
            model_name='motivationletterrubricreview',
            name='composition_penalty',
            field=models.CharField(choices=[('0', 'Нет замечаний — 0'), ('-2', 'Незначительные проблемы — -2'), ('-5', 'Серьёзные проблемы — -5')], default='0', max_length=2, verbose_name='Последовательность изложения и композиция'),
        ),
        migrations.AddField(
            model_name='motivationletterrubricreview',
            name='current_preparation_score',
            field=models.CharField(choices=[('10', 'Да, развёрнуто и по существу — 10'), ('5', 'Да, но кратко/гипотетически — 5'), ('0', 'Нет — 0')], default='0', max_length=2, verbose_name='Тема №4: текущая подготовка'),
        ),
        migrations.AddField(
            model_name='motivationletterrubricreview',
            name='higher_education_value_score',
            field=models.CharField(choices=[('10', 'Да, развёрнуто и по существу — 10'), ('5', 'Да, но кратко/гипотетически — 5'), ('0', 'Нет — 0')], default='0', max_length=2, verbose_name='Тема №7: значимость высшего образования'),
        ),
        migrations.AddField(
            model_name='motivationletterrubricreview',
            name='is_too_short',
            field=models.BooleanField(default=False, verbose_name='Менее 1000 символов'),
        ),
        migrations.AddField(
            model_name='motivationletterrubricreview',
            name='next_year_preparation_score',
            field=models.CharField(choices=[('10', 'Да, развёрнуто и по существу — 10'), ('5', 'Да, но кратко/гипотетически — 5'), ('0', 'Нет — 0')], default='0', max_length=2, verbose_name='Тема №6: подготовка в следующем учебном году'),
        ),
        migrations.AddField(
            model_name='motivationletterrubricreview',
            name='orthography_penalty',
            field=models.CharField(choices=[('0', 'Нет замечаний — 0'), ('-2', 'Незначительные проблемы — -2'), ('-5', 'Серьёзные проблемы — -5')], default='0', max_length=2, verbose_name='Орфография'),
        ),
        migrations.AddField(
            model_name='motivationletterrubricreview',
            name='returned_for_revision',
            field=models.BooleanField(default=False, verbose_name='Рекомендовано вернуть на доработку'),
        ),
        migrations.AddField(
            model_name='motivationletterrubricreview',
            name='reviewer_comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий проверяющего'),
        ),
        migrations.AddField(
            model_name='motivationletterrubricreview',
            name='score_capped_for_short_length',
            field=models.BooleanField(default=False, help_text='По критериям максимум 85 для такого объёма не ставится', verbose_name='Для текста 1000–1500 символов применён потолок оценки'),
        ),
        migrations.AddField(
            model_name='motivationletterrubricreview',
            name='specialty_choice_score',
            field=models.CharField(choices=[('15', 'Да, развёрнуто и материалы учтены — 15'), ('8', 'Да, но кратко/гипотетически, материалы учтены — 8'), ('3', 'Да, но кратко/гипотетически, материалы не учтены — 3'), ('0', 'Нет — 0')], default='0', max_length=2, verbose_name='Тема №2: выбор специальности'),
        ),
        migrations.AddField(
            model_name='motivationletterrubricreview',
            name='style_penalty',
            field=models.CharField(choices=[('0', 'Нет замечаний — 0'), ('-2', 'Незначительные проблемы — -2'), ('-5', 'Серьёзные проблемы — -5')], default='0', max_length=2, verbose_name='Точность и выразительность речи'),
        ),
        migrations.AddField(
            model_name='motivationletterrubricreview',
            name='support_criticality_score',
            field=models.CharField(choices=[('10', 'Да, развёрнуто и по существу — 10'), ('5', 'Да, но кратко/гипотетически — 5'), ('0', 'Нет — 0')], default='0', max_length=2, verbose_name='Тема №8: критичность поддержки'),
        ),
        migrations.AddField(
            model_name='motivationletterrubricreview',
            name='suspected_ai_generated',
            field=models.BooleanField(default=False, verbose_name='Есть признаки написания нейросетью'),
        ),
        migrations.AddField(
            model_name='motivationletterrubricreview',
            name='syntax_penalty',
            field=models.CharField(choices=[('0', 'Нет замечаний — 0'), ('-2', 'Незначительные проблемы — -2'), ('-5', 'Серьёзные проблемы — -5')], default='0', max_length=2, verbose_name='Синтаксис'),
        ),
        migrations.AddField(
            model_name='motivationletterrubricreview',
            name='university_choice_score',
            field=models.CharField(choices=[('15', 'Да, развёрнуто и материалы учтены — 15'), ('8', 'Да, но кратко/гипотетически, материалы учтены — 8'), ('3', 'Да, но кратко/гипотетически, материалы не учтены — 3'), ('0', 'Нет — 0')], default='0', max_length=2, verbose_name='Тема №3: выбор вуза'),
        ),
        migrations.AlterField(
            model_name='motivationletter',
            name='admin_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Введите значение от 0 до 85', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(85)], verbose_name='Итоговый балл'),
        ),
        migrations.AlterField(
            model_name='motivationletterrubricreview',
            name='extra',
            field=models.TextField(blank=True, default='', verbose_name='Дополнительные данные'),
        ),
        migrations.AlterField(
            model_name='motivationletterrubricreview',
            name='hobbies',
            field=models.TextField(blank=True, default='', verbose_name='Увлечения'),
        ),
        migrations.AlterField(
            model_name='motivationletterrubricreview',
            name='olympiads',
            field=models.TextField(blank=True, default='', verbose_name='Участие в олимпиадах'),
        ),
        migrations.AlterField(
            model_name='motivationletterrubricreview',
            name='preferred_universities',
            field=models.TextField(blank=True, default='', verbose_name='Предпочитаемые вузы'),
        ),
        migrations.AlterField(
            model_name='motivationletterrubricreview',
            name='prep_subjects',
            field=models.TextField(blank=True, default='', verbose_name='Предметы для подготовки'),
        ),
        migrations.AlterField(
            model_name='motivationletterrubricreview',
            name='relocation',
            field=models.TextField(blank=True, default='', verbose_name='Возможность переезда'),
        ),
        migrations.AlterField(
            model_name='motivationletterrubricreview',
            name='schema_version',
            field=models.CharField(blank=True, default='v2', max_length=32, verbose_name='Версия рубрики'),
        ),
        migrations.AlterField(
            model_name='motivationletterrubricreview',
            name='school_teachers',
            field=models.TextField(blank=True, default='', verbose_name='Школа и преподаватели'),
        ),
        migrations.AlterField(
            model_name='motivationletterrubricreview',
            name='specialty',
            field=models.TextField(blank=True, default='', verbose_name='Специальность'),
        ),
        migrations.AddIndex(
            model_name='motivationletterrubricreview',
            index=models.Index(fields=['is_too_short'], name='core_motiva_is_too__ec26a3_idx'),
        ),
        migrations.AddIndex(
            model_name='motivationletterrubricreview',
            index=models.Index(fields=['suspected_ai_generated'], name='core_motiva_suspect_ce2cd8_idx'),
        ),
    ]
