# Generated by Django 5.2.13 on 2026-04-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_motivationletterrubricreview_composition_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motivationletterinstruction',
            options={'ordering': ['-updated_at', '-uploaded_at'], 'verbose_name': 'Инструкция к мотивационному письму', 'verbose_name_plural': 'Инструкция к мотивационному письму'},
        ),
        migrations.AddField(
            model_name='motivationletterinstruction',
            name='button_text',
            field=models.CharField(default='Открыть инструкцию', max_length=80, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='motivationletterinstruction',
            name='text',
            field=models.TextField(blank=True, default='Перед написанием мотивационного письма ознакомьтесь с инструкциями.', verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='motivationletterinstruction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='motivationletterinstruction',
            name='url',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на инструкцию'),
        ),
        migrations.AlterField(
            model_name='motivationletterinstruction',
            name='file',
            field=models.FileField(blank=True, help_text='Устаревшее поле. Используется как запасной вариант, если ссылка на инструкцию не задана.', null=True, upload_to='motivation/instructions/', verbose_name='Общий файл инструкции'),
        ),
        migrations.AlterField(
            model_name='motivationletterinstruction',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показывать плашку'),
        ),
        migrations.AlterField(
            model_name='motivationletterinstruction',
            name='title',
            field=models.CharField(default='Инструкция к мотивационному письму', max_length=200, verbose_name='Заголовок'),
        ),
    ]
