# Generated by Django 5.2.16 on 2026-07-08 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_motivationletter_letter_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMessageTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bot_kind', models.CharField(choices=[('users', 'Users bot'), ('admin', 'Admin bot'), ('mail', 'Mail bot')], db_index=True, max_length=16)),
                ('chat_id', models.CharField(db_index=True, max_length=64)),
                ('text', models.TextField()),
                ('reply_markup', models.JSONField(blank=True, null=True)),
                ('parse_mode', models.CharField(blank=True, default='HTML', max_length=16)),
                ('disable_web_page_preview', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('RETRY', 'Retry'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('locked_by', models.CharField(blank=True, default='', max_length=128)),
                ('locked_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram message task',
                'verbose_name_plural': 'Telegram message tasks',
                'indexes': [models.Index(fields=['status', 'locked_until', 'created_at'], name='core_telegr_status_d00dec_idx'), models.Index(fields=['bot_kind', 'chat_id', 'created_at'], name='core_telegr_bot_kin_740b00_idx')],
            },
        ),
    ]
