# Generated by Django 5.2.16 on 2026-07-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_motivationletter_letter_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivationletterrubricreview',
            name='justification',
            field=models.TextField(blank=True, default='', verbose_name='Пояснение куратора'),
        ),
    ]
