# Generated by Django 5.2.16 on 2026-07-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_motivationletterrubricreview_justification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivationletterrubricreview',
            name='justification',
            field=models.TextField(blank=True, default='', verbose_name='Пояснение эксперта'),
        ),
    ]
