# Generated by Django 5.2.13 on 2026-05-04 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_motivationletterinstruction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivationletter',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Избранное письмо'),
        ),
        migrations.AlterField(
            model_name='motivationletter',
            name='admin_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Введите значение от 0 до 70', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)], verbose_name='Итоговый балл'),
        ),
        migrations.AlterField(
            model_name='motivationletterrubricreview',
            name='admission_trajectory_score',
            field=models.CharField(choices=[('10', 'Да, развёрнуто; есть обоснование; материалы учтены — 10'), ('5', 'Да, кратко/гипотетически; есть обоснование; материалы учтены — 5'), ('2', 'Да, кратко/гипотетически; нет обоснования ИЛИ материалы не учтены — 2'), ('0', 'Нет — 0')], default='0', max_length=2, verbose_name='Тема №5: траектория поступления'),
        ),
        migrations.AlterField(
            model_name='motivationletterrubricreview',
            name='schema_version',
            field=models.CharField(blank=True, default='v3.0-2026-04-25', max_length=32, verbose_name='Версия рубрики'),
        ),
        migrations.AlterField(
            model_name='motivationletterrubricreview',
            name='score_capped_for_short_length',
            field=models.BooleanField(default=False, help_text='По критериям максимум 70 для такого объёма не ставится', verbose_name='Для текста 1000–1500 символов применён потолок оценки'),
        ),
        migrations.AlterField(
            model_name='motivationletterrubricreview',
            name='specialty_choice_score',
            field=models.CharField(choices=[('10', 'Да, развёрнуто и материалы учтены — 10'), ('5', 'Да, но кратко/гипотетически, материалы учтены — 5'), ('2', 'Да, но кратко/гипотетически, материалы не учтены — 2'), ('0', 'Нет — 0')], default='0', max_length=2, verbose_name='Тема №2: выбор специальности'),
        ),
        migrations.AlterField(
            model_name='motivationletterrubricreview',
            name='university_choice_score',
            field=models.CharField(choices=[('10', 'Да, развёрнуто и материалы учтены — 10'), ('5', 'Да, но кратко/гипотетически, материалы учтены — 5'), ('2', 'Да, но кратко/гипотетически, материалы не учтены — 2'), ('0', 'Нет — 0')], default='0', max_length=2, verbose_name='Тема №3: выбор вуза'),
        ),
    ]
