# Generated by Django 5.2.14 on 2026-06-08 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать плашку')),
                ('title', models.CharField(default='Инструкция к собеседованию', max_length=120, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, default='Перед собеседованием ознакомься с инструкцией.', verbose_name='Текст')),
                ('url', models.URLField(blank=True, default='', validators=[django.core.validators.URLValidator()], verbose_name='Ссылка на инструкцию')),
                ('button_text', models.CharField(default='Открыть инструкцию', max_length=60, verbose_name='Текст кнопки')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Инструкция к собеседованию',
                'verbose_name_plural': 'Инструкция к собеседованию',
            },
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='selection_step',
            field=models.CharField(choices=[('form', 'Анкета'), ('test', 'Тестирование способностей'), ('ml', 'Мотивационное письмо'), ('video', 'Видеовизитка'), ('interview_prep', 'Подготовка к собеседованию'), ('after_interview', 'После собеседования')], db_index=True, default='form', max_length=32),
        ),
    ]
