# Generated by Django 5.2.11 on 2026-02-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='admission_path',
            field=models.CharField(blank=True, max_length=10000, verbose_name='Ты планируешь поступать по ЕГЭ или олимпиадам?'),
        ),
    ]
