# Generated by Django 5.2.14 on 2026-06-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar_form', '0002_interviewinstruction_alter_userinfo_selection_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='after_interview_documents_ready',
            field=models.BooleanField(default=False, verbose_name='Я готов(-а) предоставить документы для подтверждения анкетных данных, в случае моего прохождения в программу'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='after_interview_parents_notified',
            field=models.BooleanField(default=False, verbose_name='Я сообщил(-а) родителям/ законным представителям о том, что принимаю участие в отборе'),
        ),
    ]
