# Generated by Django 5.2.11 on 2026-02-28 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar_form', '0002_alter_userinfo_admission_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='agree_privacy_policy',
            field=models.BooleanField(null=True, verbose_name='Согласен(-на) с Политикой конфиденциальности'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='agree_program_conditions',
            field=models.BooleanField(null=True, verbose_name='Ознакомился(-ась) с условиями Благотворительной программы “Поддержи таланты”'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='agree_documents',
            field=models.BooleanField(null=True, verbose_name='В случае утверждения участия в программе обязуюсь предоставить в Фонд документы, подтверждающие сведения обо мне'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='agree_processing',
            field=models.BooleanField(null=True, verbose_name='Даю согласие на обработку персональных данных'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='city',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='class_profile',
            field=models.CharField(blank=True, help_text='при наличии', max_length=255, verbose_name='Профиль класса'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='family_material_status',
            field=models.CharField(blank=True, choices=[('1', 'Иногда не хватает денег на необходимые продукты питания'), ('2', 'На еду денег хватает, но на других ежедневных расходах приходится себя ограничивать'), ('3', 'На ежедневные расходы хватает, но покупка одежды уже представляет трудность'), ('4', 'На еду и одежду хватает, но покупка техники (телевизор, холодильник и т.п.) представляет трудности'), ('5', 'Достаточно обеспечены материально, но для покупки автомобиля и дорогостоящего отпуска пришлось бы залезть в долги'), ('6', 'Материально обеспечены, можем позволить себе дорогостоящий отпуск и покупку автомобиля'), ('99', 'Затрудняюсь ответить')], db_index=True, max_length=2, null=True, verbose_name='Как бы ты оценил(-а) материальное положение вашей семьи?'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='foundation_help',
            field=models.CharField(blank=True, max_length=10000, verbose_name='Какую помощь ты хочешь получить от Фонда?'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='has_pc_with_internet',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Есть ли у тебя компьютер/ноутбук с доступом в интернет?”'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='heard_about_program',
            field=models.CharField(blank=True, max_length=255, verbose_name='Как ты узнал(-а) о программе Фонда?'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='next_year_class_digit',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)], verbose_name='Класс в 2026-2027 учебном году'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='olympiad_plans',
            field=models.CharField(blank=True, help_text='если не планируешь участвовать, поставь прочерк', max_length=10000, verbose_name='Планы участия в олимпиадах'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='other_factors',
            field=models.CharField(blank=True, max_length=10000, verbose_name='Какие-либо иные обстоятельства, о которых ты хотел(-а) бы сообщить'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='preparation_plan',
            field=models.CharField(blank=True, max_length=10000, verbose_name='Как ты планируешь свою подготовку к поступлению на следующий год?'),
        ),
    ]
