# Generated by Django 5.2.11 on 2026-03-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar_form', '0003_userinfo_agree_privacy_policy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='has_pc_with_internet',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Есть ли у тебя компьютер/ноутбук с доступом в интернет?'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='olympiad_plans',
            field=models.CharField(blank=True, help_text='Если не планируешь участвовать, поставь прочерк', max_length=10000, verbose_name='Планы участия в олимпиадах'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='selection_step',
            field=models.CharField(choices=[('form', 'Анкета'), ('test', 'Тестирование способностей'), ('ml', 'Мотивационное письмо'), ('video', 'Видеовизитка'), ('interview_prep', 'Подготовка к собеседованию')], db_index=True, default='form', max_length=32),
        ),
    ]
