# Generated by Django 5.2.11 on 2026-03-02 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar_form', '0004_alter_userinfo_has_pc_with_internet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='avg_math_last_2_periods',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='avg_profile_subjects_last_2_periods',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='avg_russian_last_2_periods',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='agree_documents',
            field=models.BooleanField(null=True, verbose_name='В случае утверждения участия в программе обязуюсь предоставить в Фонд документы, подтверждающие предоставленные данные'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='agree_privacy_policy',
            field=models.BooleanField(null=True, verbose_name='Согласен(-на) с Политикой конфиденциальности (дефис потерялся) (ссылка: https://disk.yandex.ru/d/I2-TWTBEYwWdXw)'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='agree_processing',
            field=models.BooleanField(null=True, verbose_name='Даю согласие на обработку персональных данных (ссылка: https://disk.yandex.ru/d/kme9vXodYjntrA)'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='agree_program_conditions',
            field=models.BooleanField(null=True, verbose_name='Ознакомился(-ась) с условиями Благотворительной программы “Поддержи таланты” (ссылка: https://disk.yandex.ru/d/ESiT-bmIM6r6dQ)'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avg_grade_last_period',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Например: 4.57 или 8.92 (зависит от шкалы в школе).', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Средний балл успеваемости за последний отчетный период'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='subject_grades',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Средний балл по профильным предметам за последние 2 отчетных периода'),
        ),
    ]
