# Generated by Django 5.2.16 on 2026-07-13 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar_form', '0004_alter_userinfo_avg_grade_last_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avg_grade_last_period',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Например: 4.57 или 8.92 (зависит от шкалы в школе)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Средний балл успеваемости за последний отчетный период'),
        ),
    ]
