# Generated by Django 5.2.16 on 2026-07-13 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar_form', '0005_alter_userinfo_avg_grade_last_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avg_grade_last_period',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Например: 4.57 или 8.92 (зависит от шкалы в школе).', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Средний балл успеваемости за последний отчетный период'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('MAN', 'Мужчина'), ('WOMAN', 'Женщина')], max_length=10, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='has_alumni_sibling',
            field=models.BooleanField(default=False, verbose_name='Сиблинг выпускника (внутреннее)'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='has_breadwinner_loss',
            field=models.BooleanField(default=False, verbose_name='Потеря кормильца (внутреннее)'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='has_candidate_disability',
            field=models.BooleanField(default=False, verbose_name='Инвалидность кандидата (внутреннее)'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='has_relative_disability',
            field=models.BooleanField(default=False, verbose_name='Инвалидность близкого (внутреннее)'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='internal_study_profile',
            field=models.CharField(blank=True, choices=[('it', 'IT'), ('phys_math', 'Физмат'), ('medic', 'Врач'), ('chem_bio', 'Химбио'), ('geo_eco', 'География / экология'), ('arch_design', 'Архитектура / строительство / дизайн'), ('humanities', 'Гуманитарий'), ('other', 'Прочее')], db_index=True, help_text='Стафф-поле. Используется в сводке.', max_length=32, null=True, verbose_name='Учебный профиль (внутренний)'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='is_large_family',
            field=models.BooleanField(default=False, verbose_name='Многодетность (внутреннее)'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='is_orphan_or_under_guardianship',
            field=models.BooleanField(default=False, verbose_name='Сирота / под опекой (внутреннее)'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='is_parent_in_svo',
            field=models.BooleanField(default=False, verbose_name='Родитель на СВО (внутреннее)'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='is_parent_pensioner',
            field=models.BooleanField(default=False, verbose_name='Родитель пенсионер (внутреннее)'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='is_single_parent_family',
            field=models.BooleanField(default=False, verbose_name='Неполная семья (внутреннее)'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='life_situation_notes',
            field=models.TextField(blank=True, help_text='Коротко: что важно учесть при рассмотрении анкеты.', null=True, verbose_name='Особенность жизненной ситуации (внутреннее)'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='settlement_type',
            field=models.CharField(blank=True, choices=[('big_city', 'Крупный город'), ('mid_city', 'Средний город'), ('small_settlement', 'Малое поселение')], db_index=True, max_length=32, null=True, verbose_name='Тип населённого пункта (внутреннее)'),
        ),
    ]
