# Generated by Django 5.2.11 on 2026-03-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar_form', '0005_remove_userinfo_avg_math_last_2_periods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='agree_privacy_policy',
            field=models.BooleanField(null=True, verbose_name='Согласен(-на) с Политикой конфиденциальности (ссылка: https://disk.yandex.ru/d/I2-TWTBEYwWdXw)'),
        ),
    ]
