# Generated by Django 5.2.11 on 2026-03-15 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar_form', '0006_alter_userinfo_agree_privacy_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать плашку')),
                ('title', models.CharField(default='Инструкция к видеовизитке', max_length=120, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, default='Перед записью ознакомься с требованиями.', verbose_name='Текст')),
                ('url', models.URLField(validators=[django.core.validators.URLValidator()], verbose_name='Ссылка на инструкцию')),
                ('button_text', models.CharField(default='Открыть инструкцию', max_length=60, verbose_name='Текст кнопки')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Инструкция к видеовизитке',
                'verbose_name_plural': 'Инструкция к видеовизитке',
            },
        ),
        migrations.AddField(
            model_name='scholarvideo',
            name='online_school_course',
            field=models.TextField(blank=True, default='', help_text='Укажи онлайн-школу и курс в свободной форме', verbose_name='Онлайн-школа и курс'),
        ),
        migrations.AddField(
            model_name='scholarvideo',
            name='schedule_file',
            field=models.FileField(blank=True, null=True, upload_to='scholar_video_schedules/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='График занятий'),
        ),
    ]
