# Generated by Django 5.2.12 on 2026-04-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar_form', '0007_videoinstruction_scholarvideo_online_school_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarvideo',
            name='schedule_yandex_disk_error',
            field=models.TextField(blank=True, default='', verbose_name='РћС€РёР±РєР° РІС‹РіСЂСѓР·РєРё РіСЂР°С„РёРєР° РЅР° РЇРЅРґРµРєСЃ Р”РёСЃРє'),
        ),
        migrations.AddField(
            model_name='scholarvideo',
            name='schedule_yandex_disk_path',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='РџСѓС‚СЊ РіСЂР°С„РёРєР° РЅР° РЇРЅРґРµРєСЃ Р”РёСЃРєРµ'),
        ),
        migrations.AddField(
            model_name='scholarvideo',
            name='schedule_yandex_disk_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Р“СЂР°С„РёРє Р·Р°РіСЂСѓР¶РµРЅ РЅР° РЇРЅРґРµРєСЃ Р”РёСЃРє'),
        ),
        migrations.AddField(
            model_name='scholarvideo',
            name='yandex_disk_error',
            field=models.TextField(blank=True, default='', verbose_name='РћС€РёР±РєР° РІС‹РіСЂСѓР·РєРё РЅР° РЇРЅРґРµРєСЃ Р”РёСЃРє'),
        ),
        migrations.AddField(
            model_name='scholarvideo',
            name='yandex_disk_path',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='РџСѓС‚СЊ РЅР° РЇРЅРґРµРєСЃ Р”РёСЃРєРµ'),
        ),
        migrations.AddField(
            model_name='scholarvideo',
            name='yandex_disk_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Р—Р°РіСЂСѓР¶РµРЅРѕ РЅР° РЇРЅРґРµРєСЃ Р”РёСЃРє'),
        ),
    ]
