# Generated by Django 5.2.12 on 2026-04-07 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholar_form', '0008_scholarvideo_schedule_yandex_disk_error_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarvideo',
            name='schedule_yandex_disk_error',
        ),
        migrations.RemoveField(
            model_name='scholarvideo',
            name='schedule_yandex_disk_path',
        ),
        migrations.RemoveField(
            model_name='scholarvideo',
            name='schedule_yandex_disk_uploaded_at',
        ),
        migrations.RemoveField(
            model_name='scholarvideo',
            name='yandex_disk_error',
        ),
        migrations.RemoveField(
            model_name='scholarvideo',
            name='yandex_disk_path',
        ),
        migrations.RemoveField(
            model_name='scholarvideo',
            name='yandex_disk_uploaded_at',
        ),
    ]
