# Generated by Django 5.2.13 on 2026-05-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar_form', '0010_scholarvideo_schedule_yandex_disk_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarvideo',
            name='online_school_choice_reason',
            field=models.TextField(blank=True, default='', verbose_name='Онлайн-школы: обоснование выбора'),
        ),
        migrations.AddField(
            model_name='scholarvideo',
            name='online_school_extra_help',
            field=models.TextField(blank=True, default='', verbose_name='Онлайн-школы: нужна ли дополнительная помощь'),
        ),
        migrations.AddField(
            model_name='scholarvideo',
            name='online_school_interview_questions',
            field=models.TextField(blank=True, default='', verbose_name='Онлайн-школы: вопросы для обсуждения на собеседовании'),
        ),
        migrations.AddField(
            model_name='scholarvideo',
            name='online_school_observations',
            field=models.TextField(blank=True, default='', verbose_name='Онлайн-школы: наблюдения и выводы'),
        ),
        migrations.AddField(
            model_name='scholarvideo',
            name='online_school_prior_experience',
            field=models.TextField(blank=True, default='', verbose_name='Онлайн-школы: предыдущий опыт'),
        ),
        migrations.AddField(
            model_name='scholarvideo',
            name='online_school_selected_courses',
            field=models.TextField(blank=True, default='', verbose_name='Онлайн-школы: выбранные курсы'),
        ),
        migrations.AddField(
            model_name='scholarvideo',
            name='online_school_used_materials',
            field=models.TextField(blank=True, default='', verbose_name='Онлайн-школы: опирался ли на предоставленные материалы'),
        ),
        migrations.AddField(
            model_name='scholarvideo',
            name='schedule_activities_time',
            field=models.TextField(blank=True, default='', verbose_name='График: время на допактивности, кружки и спорт'),
        ),
        migrations.AddField(
            model_name='scholarvideo',
            name='schedule_exam_prep_time',
            field=models.TextField(blank=True, default='', verbose_name='График: время на подготовку к ЕГЭ и олимпиадам'),
        ),
        migrations.AddField(
            model_name='scholarvideo',
            name='schedule_extra_help',
            field=models.TextField(blank=True, default='', verbose_name='График: нужна ли дополнительная помощь'),
        ),
        migrations.AddField(
            model_name='scholarvideo',
            name='schedule_homework_time',
            field=models.TextField(blank=True, default='', verbose_name='График: время на домашнюю работу'),
        ),
        migrations.AddField(
            model_name='scholarvideo',
            name='schedule_interview_questions',
            field=models.TextField(blank=True, default='', verbose_name='График: вопросы для обсуждения на собеседовании'),
        ),
        migrations.AddField(
            model_name='scholarvideo',
            name='schedule_realistic_assessment',
            field=models.TextField(blank=True, default='', verbose_name='График: реалистичность плана'),
        ),
        migrations.AddField(
            model_name='scholarvideo',
            name='schedule_rest_time',
            field=models.TextField(blank=True, default='', verbose_name='График: время на отдых'),
        ),
        migrations.AddField(
            model_name='scholarvideo',
            name='schedule_school_day',
            field=models.TextField(blank=True, default='', verbose_name='График: обычный школьный день'),
        ),
        migrations.AddField(
            model_name='scholarvideo',
            name='schedule_used_materials',
            field=models.TextField(blank=True, default='', verbose_name='График: опирался ли на предоставленные материалы'),
        ),
        migrations.AddField(
            model_name='scholarvideo',
            name='schedule_weekend_day',
            field=models.TextField(blank=True, default='', verbose_name='График: обычный выходной'),
        ),
        migrations.AddField(
            model_name='scholarvideo',
            name='transcript_error',
            field=models.TextField(blank=True, verbose_name='Ошибка транскрибации'),
        ),
        migrations.AddField(
            model_name='scholarvideo',
            name='transcript_status',
            field=models.CharField(choices=[('PENDING', 'Ожидает'), ('PROCESSING', 'В работе'), ('DONE', 'Готово'), ('FAILED', 'Ошибка')], default='PENDING', max_length=20, verbose_name='Статус транскрибации'),
        ),
        migrations.AddField(
            model_name='scholarvideo',
            name='transcript_text',
            field=models.TextField(blank=True, default='', verbose_name='Транскрипция видеовизитки'),
        ),
        migrations.AddField(
            model_name='scholarvideo',
            name='transcript_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='form_status',
            field=models.CharField(choices=[('draft', 'Не отправлена'), ('submitted', 'Отправлена'), ('revision', 'На дописывание'), ('clarification', 'На уточнении'), ('approved', 'Принята'), ('rejected', 'Отклонена')], db_index=True, default='draft', max_length=20, verbose_name='Статус анкеты'),
        ),
    ]
