# Generated by Django 5.2.11 on 2026-02-20 17:08

import django.core.validators
import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file', models.FileField(upload_to='doc_templates/', validators=[django.core.validators.FileExtensionValidator(['docx'])], verbose_name='Файл шаблона (.docx)')),
                ('required_params', models.JSONField(blank=True, default=dict, verbose_name='Требуемые параметры')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=documents.models.upload_to_path)),
                ('user_file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('caption', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'На проверке'), ('APPROVED', 'Подтверждено'), ('QUESTION', 'Уточнить'), ('PENDING_SIGNATURE', 'Ожидает подписи'), ('SIGNED', 'Подписан'), ('REJECTED_SIGNATURE', 'Подпись отклонена')], default='PENDING', max_length=18)),
                ('only_staff_comment', models.TextField(blank=True, null=True)),
                ('uploaded_by_staff', models.BooleanField(default=False)),
                ('related_documents', models.ManyToManyField(blank=True, related_name='document_relations', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
