# Generated by Django 5.2.11 on 2026-02-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_by_tutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewresult',
            name='admission_way',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Существует несколько траекторий поступления, опиши ту, которую планируешь использовать сейчас', max_length=255, verbose_name='Планируемая траектория поступления'),
        ),
    ]
