# Generated by Django 5.2.14 on 2026-05-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_by_tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='video_link_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='video_link_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='interview',
            name='video_mime',
            field=models.CharField(blank=True, default='', max_length=127),
        ),
        migrations.AddField(
            model_name='interview',
            name='video_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='interview',
            name='video_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='video_source_type',
            field=models.CharField(blank=True, choices=[('', 'Local file'), ('yandex_disk_path', 'Yandex Disk path'), ('yandex_public_url', 'Yandex Disk public URL')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='interview',
            name='video_yandex_disk_path',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='interview',
            name='video_yandex_disk_url',
            field=models.TextField(blank=True, verbose_name='Yandex Disk video link/path'),
        ),
    ]
