# Generated by Django 5.2.14 on 2026-06-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_by_tutor', '0002_interview_video_link_checked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='filled_template',
            field=models.FileField(blank=True, null=True, upload_to='interview/filled_templates/', verbose_name='Заполненный шаблон интервью'),
        ),
    ]
