# Generated by Django 5.2.11 on 2026-03-01 14:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_by_tutor', '0002_alter_interviewresult_admission_way'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testassignment',
            name='revision_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отправлено на дописывание'),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='revision_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_requested_tests', to=settings.AUTH_USER_MODEL, verbose_name='Отправил на дописывание'),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='revision_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий для дописывания'),
        ),
        migrations.AlterField(
            model_name='testassignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Назначено'), ('in_progress', 'В процессе'), ('needs_revision', 'На дописывание'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], db_index=True, default='assigned', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='TestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название теста')),
                ('external_url', models.URLField(blank=True, verbose_name='Ссылка на прохождение')),
                ('instructions', models.TextField(blank=True, verbose_name='Инструкции/Комментарий')),
                ('default_due_days', models.PositiveIntegerField(blank=True, help_text='Если задано, дедлайн посчитается как assigned_at + N дней', null=True, verbose_name='Дедлайн (дней от назначения)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_test_templates', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Шаблон теста',
                'verbose_name_plural': 'Шаблоны тестов',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='testassignment',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='review_by_tutor.testtemplate', verbose_name='Шаблон'),
        ),
    ]
