# Generated by Django 5.2.16 on 2026-07-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_by_tutor', '0003_interview_filled_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewresult',
            name='admission_way',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Планирет поступать по ЕГЭ или олимпиадам?', max_length=255, verbose_name='Планируемая траектория поступления'),
        ),
    ]
