# Generated by Django 5.2.11 on 2026-03-04 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_by_tutor', '0003_testassignment_revision_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать плашку')),
                ('title', models.CharField(default='Инструкция к тестированию', max_length=120, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, default='Перед выполнением теста ознакомьтесь с инструкцией.', verbose_name='Текст')),
                ('url', models.URLField(validators=[django.core.validators.URLValidator()], verbose_name='Ссылка на инструкцию')),
                ('button_text', models.CharField(default='Открыть инструкцию', max_length=60, verbose_name='Текст кнопки')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Инструкция к тестированию',
                'verbose_name_plural': 'Инструкция к тестированию',
            },
        ),
        migrations.RemoveField(
            model_name='testassignment',
            name='percentile',
        ),
        migrations.RemoveField(
            model_name='testassignment',
            name='result_score',
        ),
        migrations.AddField(
            model_name='testassignment',
            name='percentile_a',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Перцентиль по шкале A (0–100)', max_digits=5, null=True, verbose_name='Перцентиль A'),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='percentile_b',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Перцентиль по шкале B (0–100)', max_digits=5, null=True, verbose_name='Перцентиль B'),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='percentile_c',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Перцентиль по шкале C (0–100)', max_digits=5, null=True, verbose_name='Перцентиль C'),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='score_a',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Баллы A'),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='score_b',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Баллы B'),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='score_c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Баллы C'),
        ),
    ]
