# Generated by Django 5.2.16 on 2026-07-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_by_tutor', '0004_alter_interviewresult_admission_way'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewresult',
            name='admission_way',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Существует несколько траекторий поступления, опиши ту, которую планируешь использовать сейчас', max_length=255, verbose_name='Планируемая траектория поступления'),
        ),
    ]
