# Generated by Django 5.2.12 on 2026-04-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_by_tutor', '0005_remove_testassignment_percentile_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testassignment',
            name='logical_grade',
        ),
        migrations.RemoveField(
            model_name='testassignment',
            name='logical_percentile',
        ),
        migrations.RemoveField(
            model_name='testassignment',
            name='numeric_grade',
        ),
        migrations.RemoveField(
            model_name='testassignment',
            name='numeric_percentile',
        ),
        migrations.RemoveField(
            model_name='testassignment',
            name='verbal_grade',
        ),
        migrations.RemoveField(
            model_name='testassignment',
            name='verbal_percentile',
        ),
        migrations.AddField(
            model_name='testassignment',
            name='percentile_a',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Перцентиль по шкале A (0–100)', max_digits=5, null=True, verbose_name='Перцентиль A'),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='percentile_b',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Перцентиль по шкале B (0–100)', max_digits=5, null=True, verbose_name='Перцентиль B'),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='percentile_c',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Перцентиль по шкале C (0–100)', max_digits=5, null=True, verbose_name='Перцентиль C'),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='score_a',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Баллы A'),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='score_b',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Баллы B'),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='score_c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Баллы C'),
        ),
    ]
