# Generated by Django 5.2.13 on 2026-04-07 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_by_tutor', '0006_remove_testassignment_logical_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testassignment',
            name='percentile_a',
        ),
        migrations.RemoveField(
            model_name='testassignment',
            name='percentile_b',
        ),
        migrations.RemoveField(
            model_name='testassignment',
            name='percentile_c',
        ),
        migrations.RemoveField(
            model_name='testassignment',
            name='score_a',
        ),
        migrations.RemoveField(
            model_name='testassignment',
            name='score_b',
        ),
        migrations.RemoveField(
            model_name='testassignment',
            name='score_c',
        ),
        migrations.AddField(
            model_name='testassignment',
            name='logical_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=1, verbose_name='Грейд логического теста'),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='logical_percentile',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Значение от 1 до 99', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Перцентиль логического теста'),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='numeric_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=1, verbose_name='Грейд числового теста'),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='numeric_percentile',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Значение от 1 до 99', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Перцентиль числового теста'),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='verbal_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=1, verbose_name='Грейд вербального теста'),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='verbal_percentile',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Значение от 1 до 99', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Перцентиль вербального теста'),
        ),
    ]
