# Generated by Django 4.2 on 2026-08-24 16:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0004_document_slot_label'),
        ('scholar_form', '0003_userinfo_after_interview_documents_ready_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyIncomeCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('staff_draft', 'Черновик сотрудника'), ('revision', 'На доработке'), ('pending_review', 'На проверке'), ('approved', 'Подтверждено')], db_index=True, default='staff_draft', max_length=32, verbose_name='Статус')),
                ('family_members_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество членов семьи')),
                ('family_members_description', models.TextField(verbose_name='Состав семьи и занятия')),
                ('family_characteristics', models.TextField(blank=True, verbose_name='Характеристика семьи')),
                ('low_income_recognized', models.BooleanField(blank=True, null=True, verbose_name='Семья признана малоимущей')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('user_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_income_case', to='scholar_form.userinfo', verbose_name='Анкета пользователя')),
            ],
            options={
                'verbose_name': 'Карточка семьи и дохода',
                'verbose_name_plural': 'Карточки семьи и дохода',
            },
        ),
        migrations.CreateModel(
            name='FamilyIncomeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('family_characteristic', 'Подтверждение статуса'), ('income', 'Доход'), ('social_benefit', 'Социальные выплаты'), ('other', 'Иные документы')], db_index=True, max_length=32, verbose_name='Категория')),
                ('candidate_comment', models.TextField(verbose_name='Комментарий кандидата')),
                ('staff_comment', models.TextField(blank=True, verbose_name='Комментарий сотрудника')),
                ('review_status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Подтверждено'), ('clarification', 'Требуется уточнение')], db_index=True, default='pending', max_length=20, verbose_name='Статус проверки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_income_documents_added', to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_income_documents', to='family_income.familyincomecase', verbose_name='Карточка')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='family_income_link', to='documents.document', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Документ семьи и дохода',
                'verbose_name_plural': 'Документы семьи и дохода',
            },
        ),
        migrations.CreateModel(
            name='IncomeYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True, verbose_name='Год')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Год дохода',
                'verbose_name_plural': 'Годы дохода',
                'ordering': ('sort_order', '-year'),
            },
        ),
        migrations.CreateModel(
            name='SocialBenefitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('is_other', models.BooleanField(default=False, verbose_name='Вариант «другое»')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Тип социальной выплаты',
                'verbose_name_plural': 'Типы социальных выплат',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SocialBenefitEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='Получатель')),
                ('other_benefit_name', models.CharField(blank=True, max_length=255, verbose_name='Иная выплата')),
                ('benefit_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='family_income.socialbenefittype', verbose_name='Тип выплаты')),
                ('family_income_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_benefit_evidence', to='family_income.familyincomedocument', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Сведения о социальной выплате',
                'verbose_name_plural': 'Сведения о социальных выплатах',
            },
        ),
        migrations.CreateModel(
            name='IncomeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255, verbose_name='Чей документ')),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Общая сумма')),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сумма после налога')),
                ('average_monthly_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Средний годовой доход')),
                ('months_received', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Месяцев получения')),
                ('absence_reason', models.TextField(blank=True, verbose_name='Причина отсутствия сумм')),
                ('staff_decision_comment', models.TextField(blank=True, verbose_name='Комментарий сотрудника об учёте')),
                ('family_income_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='income_evidence', to='family_income.familyincomedocument', verbose_name='Документ')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_evidence', to='family_income.incomeyear', verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Сведения о доходе',
                'verbose_name_plural': 'Сведения о доходах',
            },
        ),
        migrations.CreateModel(
            name='FamilyIncomeInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('version', models.CharField(max_length=64, unique=True, verbose_name='Версия')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликована'), ('archived', 'Архив')], default='draft', max_length=16, verbose_name='Статус')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубликована')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_income_instructions_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Инструкция по семье и доходу',
                'verbose_name_plural': 'Инструкции по семье и доходу',
            },
        ),
        migrations.CreateModel(
            name='FamilyIncomeDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_per_member', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Среднемесячный доход на члена семьи')),
                ('comment', models.TextField(verbose_name='Пояснение')),
                ('is_low_income_recognized', models.BooleanField(blank=True, null=True, verbose_name='Семья признана малоимущей за год')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='family_income.familyincomecase', verbose_name='Карточка')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_income_decisions_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_income_decisions_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='family_income.incomeyear', verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Ручной итог дохода',
                'verbose_name_plural': 'Ручные итоги дохода',
            },
        ),
        migrations.CreateModel(
            name='FamilyIncomeAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Действие')),
                ('target_model', models.CharField(max_length=100, verbose_name='Модель объекта')),
                ('target_id', models.PositiveBigIntegerField(verbose_name='ID объекта')),
                ('before', models.JSONField(blank=True, default=dict, verbose_name='До изменения')),
                ('after', models.JSONField(blank=True, default=dict, verbose_name='После изменения')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_income_audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='family_income.familyincomecase', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Событие аудита семьи и дохода',
                'verbose_name_plural': 'События аудита семьи и дохода',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='familyincomeinstruction',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('status',), name='family_income_one_published_instruction'),
        ),
        migrations.AddIndex(
            model_name='familyincomedocument',
            index=models.Index(fields=['case', 'category'], name='family_inco_case_id_055da6_idx'),
        ),
        migrations.AddConstraint(
            model_name='familyincomedecision',
            constraint=models.UniqueConstraint(fields=('case', 'year'), name='family_income_unique_decision_year'),
        ),
    ]
