# Generated by Django 4.2 on 2026-09-11 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family_income', '0008_family_income_instruction_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyincomedecision',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='family_income.incomeyear', verbose_name='Год архивного итога'),
        ),
        migrations.AddConstraint(
            model_name='familyincomedecision',
            constraint=models.UniqueConstraint(condition=models.Q(('year__isnull', True)), fields=('case',), name='family_income_unique_current_decision'),
        ),
    ]
